<template><section class="copilot"><div class="title"><i class="pi pi-sparkles"></i> Copiloto geoespacial</div><div class="messages"><div v-if="!messages.length" class="empty">Pergunte sobre produtos, qualidade, relevo ou análises do projeto.</div><div v-for="(m,i) in messages" :key="i" class="message" :class="m.role"><b>{{m.role==='user'?'Você':'Copiloto'}}</b><p>{{m.text}}</p><small v-if="m.tools">Ferramentas: {{m.tools.join(', ')}}</small></div></div><form @submit.prevent="send"><textarea v-model="prompt" rows="2" placeholder="Ex.: compare DSM e DTM deste projeto..." :disabled="loading"></textarea><button :disabled="loading || !prompt.trim()" title="Enviar"><i :class="loading?'pi pi-spin pi-spinner':'pi pi-send'"></i></button></form></section></template>
<script setup>
import { ref, watch } from 'vue'; import { askCopilot, createCopilotThread, getCopilotThread, addCopilotMessage } from '../api/client'; import { useProjectStore } from '../stores/projectStore'; import { useMapStore } from '../stores/mapStore'
const projectStore=useProjectStore(),mapStore=useMapStore(),prompt=ref(''),loading=ref(false),messages=ref([]),threadId=ref(null)
async function loadThread(){if(!projectStore.activeProject)return;try{const key=`ortomapas.thread.${projectStore.activeProject.id}`;let id=localStorage.getItem(key);if(!id){const {data}=await createCopilotThread({projeto_id:projectStore.activeProject.id,titulo:`Copiloto - ${projectStore.activeProject.nome}`});id=data.id;localStorage.setItem(key,id)}threadId.value=Number(id);const history=await getCopilotThread(threadId.value);messages.value=(history.data.mensagens||[]).filter(m=>m.papel!=='tool').map(m=>({role:m.papel,text:m.conteudo}))}catch{messages.value=[]}}
watch(()=>projectStore.activeProject,loadThread,{immediate:true})
async function send(){const text=prompt.value.trim();if(!text)return;messages.value.push({role:'user',text});prompt.value='';loading.value=true;try{if(threadId.value) await addCopilotMessage(threadId.value,{papel:'user',conteudo:text});const {data}=await askCopilot(text,{projeto_id:projectStore.activeProject?.id,geometria:mapStore.selectedGeometry,bbox:mapStore.clipBbox});const answer=data.resposta?.answer||'Analise concluida.';messages.value.push({role:'assistant',text:answer,tools:(data.ferramentas_executadas||[]).map(x=>x.tool)});if(threadId.value) await addCopilotMessage(threadId.value,{papel:'assistant',conteudo:answer,ferramentas:data.ferramentas_executadas||[]})}catch(e){const answer=e.response?.data?.detail||'Nao foi possivel consultar o copiloto.';messages.value.push({role:'assistant',text:answer});if(threadId.value) await addCopilotMessage(threadId.value,{papel:'assistant',conteudo:answer})}finally{loading.value=false}}
</script><style scoped>.copilot{margin-top:12px;border-top:1px solid var(--border);padding-top:9px}.title{font-size:.8rem;font-weight:600;color:#7fd1b9;text-transform:uppercase}.messages{max-height:230px;overflow:auto;margin:8px 0}.empty{font-size:.75rem;color:var(--text-dim);padding:8px 0}.message{padding:7px;margin:5px 0;border-left:2px solid #40515c;background:#17242c;font-size:.75rem}.message.user{border-color:#56b4d3}.message p{margin:3px 0;white-space:pre-wrap}.message small{color:#7fd1b9}form{display:flex;gap:6px}textarea{flex:1;resize:vertical;background:var(--input-bg,#101820);color:var(--text);border:1px solid var(--border);padding:7px;font:inherit}form button{width:34px;border:1px solid #52616b;background:#17242c;color:#7fd1b9;cursor:pointer}form button:disabled{opacity:.5}
</style>
